# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76af9dba1ea158fceb3ca5b3de33f2d96854624a858c0244758fd55fc31773c3492f44e1ba00688b1813219787a40ff6a37c311d748d552dcf9fe61d74c3cb7

test:
  secret_key_base: 8877d99c897b0bb1beb4b85c707458c2ba96c9a79a584ee963e4dd4300a0006ab9164fe979629e70bc190436bc31c27f30006809b53a05f6b3b9c54ced065365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
